HIFI-469 Testing Bot Update
highfidelity/Spatial-Audio-API-Examples pull request #27
Opened 2021-03-22 18:51 UTC by roxanneskelly

update testing bot to latest spatial audio api.

2021-03-22 20:46 UTC, sabrina-shanman requested changes

2021-03-22 20:46 UTC, sabrina-shanman commented on examples/nodejs/testingbot/package.json
> +    "clean": "find ../../src -name '*.js*' -delete",
These two npm scripts are referring to javascript files which no longer exist two directories up.

2021-03-22 21:01 UTC, roxanneskelly commented on examples/nodejs/testingbot/package.json
> +    "clean": "find ../../src -name '*.js*' -delete",
Yeah, we should fix that, by simply removing them I think.

2021-03-23 18:19 UTC, zfox23 requested changes
Could you please add a README to this project directory, and update the `/README.md` to link to this folder? Thank you!

2021-03-26 21:35 UTC, roxanneskelly commented on examples/nodejs/testingbot/README.md
> +This bot will move randomly within a box that stretches from -15 to 15 on the x axis and from -5 to 15 on the y axis.
should be '-15 to 15 on the y axis'

2021-03-26 23:00 UTC, sabrina-shanman submitted a review, later dismissed

2021-03-30 16:01 UTC, howard-stearns commented on examples/nodejs/testingbot/vectors.js
> +module.exports = {randomNumberBetween, makeRandom, isWithin, length, add, subtract, multiply, divide, dot, cross, normalize, project, angleBetween, degreesBetween, radiansToDegrees};
Let's add a newline after this (and maybe within the braces as well), so that the exports are readable. (It is hard for me to get it to display in my browser.)

2021-03-30 16:10 UTC, howard-stearns commented on examples/nodejs/testingbot/main.js
> +const { Point3D, HiFiAudioAPIData, HiFiCommunicator } = require("hifi-spatial-audio");
This file (main.js) and rtcaudiosourcesinewave.js (below) are the original example, but are not used in the general industrial strength bot that this PR is about, and are not documented.  I didn't remove them from the original repo in the early days (nor from the package.json scripts property) because we had not yet established what we trying to make available. I think having multiple different (and really unrelated) things in the same directory contributed to the idea of not originally bringing any of this over to Spatial-Audio-API-Examples in the first wave.

Now that we are bringing it over, I think we should drop these two from this directory (and the package.json scripts listing).  I have no opinion as to whether they should still be brought over separately as examples (separate PR, separate directory, separate README, etc.)

2021-03-30 16:12 UTC, howard-stearns commented on examples/nodejs/testingbot/generateJSON.js
> +generate();
newline after to make readable.

2021-03-30 16:15 UTC, howard-stearns commented on examples/nodejs/testingbot/preciseInterval.js
> +'use strict';
I think this functionality has been added to the API (and exported from it). 
I think we should modify the usage in this directory to pull it from the API, and then remove this file here.

2021-03-30 16:16 UTC, howard-stearns commented on examples/nodejs/testingbot/package.json
> +    "start": "node ./index.js",
see separate comment about index/main/rtcaudiosourcesinewave)

2021-03-30 16:18 UTC, howard-stearns commented on examples/nodejs/testingbot/audioSource.js
> +module.exports = AudioSource;
newline after

2021-03-30 16:47 UTC, howard-stearns commented on examples/nodejs/testingbot/generateJSON.js
> +'use strict';
I'm not sure if this file has bit-rot, or whether it pulls its weight as is. Might be best to drop it (and to remove the reference to it in package.json).

For example, it looks like it generates files with full urls to S3, but those files are included here in this PR, so there is no need to go to S3. There is also no documentation on how to customize the parameters to generate different results, and I'm not sure that it's worth including that right now.

2021-03-30 16:58 UTC, howard-stearns commented on examples/nodejs/testingbot/bot.js
> +        this.communicator.updateUserDataAndTransmit({orientationEuler});
Is this the preferred way to do this now? Should we be using quaternions?

2021-03-30 16:59 UTC, howard-stearns commented on examples/nodejs/testingbot/bot.js
> +        this.communicator.updateUserDataAndTransmit({hiFiGain});
There is also now threshold. But I think that can be added separately at some future time.

2021-03-30 19:57 UTC, howard-stearns submitted a review, later dismissed

2021-04-02 19:40 UTC, zfox23 requested changes

2021-04-02 19:40 UTC, zfox23 commented on examples/nodejs/testingbot/package.json
> +    "hifi-spatial-audio": "^0.5.1",
Run `npm i hifi-spatial-audio@latest` to update this package to the latest version, then commit the change, please!

2021-04-02 19:40 UTC, zfox23 commented on examples/nodejs/testingbot/bot.js
> +} = require("hifi-spatial-audio");
Switch to ESM import syntax, or else this example will not work with the latest version of our client library :)

```suggestion
import {
    HiFiAudioAPIData,
    Point3D,
    OrientationEuler3D,
    HiFiCommunicator,
    HiFiConstants
} = from "hifi-spatial-audio";

```

2021-04-02 19:40 UTC, zfox23 commented on examples/nodejs/testingbot/bot.js
> +const { default: UnsecuredJWT } = require("jose/jwt/unsecured");
`esm` doesn't play nicely with `jose`. To fix that, you'll have to do:

```suggestion
const { SignJWT } = require('jose/dist/node/cjs/jwt/sign');
const { UnsecuredJWT } = require('jose/dist/node/cjs/jwt/unsecured');
```

2021-04-02 19:40 UTC, zfox23 commented on examples/nodejs/testingbot/package.json
> +    "bandwidth": "node --unhandled-rejections=strict -- ./testBandwidth.js"
With the latest client library, you'll need:

```suggestion
    "bots": "node -r esm ./integration-test.js",
    "bandwidth": "node -r esm --unhandled-rejections=strict -- ./testBandwidth.js"
```

2021-04-02 22:01 UTC, zfox23 approved these changes

2021-04-02 22:41 UTC, merged